# Spring properties
spring:
  application:
     name: organization-service
  profiles:
    active: local

# HTTP Server
server:
  port: 8081   # HTTP (Tomcat) port

solr:
  server:
    url: http://solr:8983/solr