# Spring properties
spring:
  application:
     name: proxy-service

# HTTP Server
server:
  port: 8083   # HTTP (Tomcat) port
  
zuul:
  ignoredPatterns: /health
  stripPrefix: false
  routes:
    accounts:
      path: /accounts/**
      serviceId: account-service
    organizations:
      path: /organizations/**
      serviceId: organization-service

account-service:
  ribbon:
    ReadTimeout: 30000

organization-service:
  ribbon:
    ReadTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000